# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: pre-alpha release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build linux/amd64
      run: GOOS=linux GOARCH=amd64 go build -o rvim-linux-amd64 ./cmd/rvim
    - name: Build darwin/amd64
      run: GOOS=darwin GOARCH=amd64 go build -o rvim-macos-amd64 ./cmd/rvim
    - name: Build darwin/arm64
      run: GOOS=darwin GOARCH=arm64 go build -o rvim-macos-arm64 ./cmd/rvim
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "README.md,rvim-linux-amd64,rvim-macos-amd64,rvim-macos-arm64"
        tag: pre-alpha-${{ github.run_number }}
        commit: "main"
        prerelease: true
  
