# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: pre-alpha release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build linux/amd64
      run: GOOS=linux GOARCH=amd64 go build -o linux/amd64/rvim ./cmd/rvim
    - name: Build darwin/amd64
      run: GOOS=darwin GOARCH=amd64 go build -o darwin/amd64/rvim ./cmd/rvim
    - name: Build darwin/arm64
      run: GOOS=darwin GOARCH=arm64 go build -o darwin/arm64/rvim ./cmd/rvim
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "README.md,linux/amd64/rvim,darwin/amd64/rvim,darwin/arm64/rvim"
        tag: "pre-alpha"
        commit: "main"
        prerelease: true
  
